ORG 0X00
	SJMP 0X30
ORG 0X30
	BASE EQU 0X61
	N EQU 0X60
	I EQU R4
	J EQU R0
	TEMP EQU R1
	JLIM EQU 0X62
	MOV A,BASE
	MOV I,A;I=0
	ADD A,N
	MOV N,A;N=BASE+N LAST ELEMENT ADDRESS
OLOOP:CLR C
	  MOV A,I
	  CJNE A,N,INNERLOOP
	  SJMP EXITLOOP
INNERLOOP:CLR C
		  MOV J,BASE
		  MOV A,N
		  SUBB A,I
		  DEC A
		  ADD A,BASE
		  MOV JLIM,A
	 REP: CLR C
	 	  MOV A,J
	 	  CJNE A,JLIM,CHECKANDCHANGE
		  INC I
		  SJMP OLOOP
		  CHECKANDCHANGE:CLR C
		  				 MOV A,J
		  				 INC A
						 MOV TEMP,A
						 MOV A,@TEMP
						 SUBB A,@J
						 JC EXCHANGE
				BACKWARD:INC J
						 SJMP REP 		   
				EXCHANGE:XCH A,@TEMP
						 XCH A,@J
						 XCH A,@TEMP
						 SJMP BACKWARD
EXITLOOP:SJMP EXITLOOP
END	   		  