ORG 0X00
    SJMP 0X30
ORG 0X30
STATUS EQU R2
N EQU R3
KEY EQU 0X60
BASE EQU R0
COUNTER EQU R4
MOV COUNTER,#00
MOV STATUS,#00
COMPARE:MOV A,@BASE
        CJNE A,KEY,NOTEQUAL
EQUAL:MOV A,BASE
      MOV STATUS,A
      SJMP LOOP
NOTEQUAL:CLR C
         INC BASE
         INC COUNTER
         MOV A,COUNTER
         SUBB A,N 
         JZ LOOP
         SJMP COMPARE
LOOP:SJMP LOOP
END

