ORG 0X00
	SJMP 0X30
ORG 0X30
SMALLEST EQU 0X60
LARGEST EQU 0X61
BASE EQU R0
N EQU R4
MOV SMALLEST,@BASE
MOV LARGEST,@BASE
INC BASE
DEC N
REPEAT:	MOV PSW,#00
		MOV A,@BASE
		CJNE A,SMALLEST,NEWSMALL
LCHECK:	MOV PSW,#00
		MOV A,@BASE
		CJNE A,LARGEST,NEWLARGE
CONTINUE:INC BASE
		DJNZ N,REPEAT
		SJMP LOOP
NEWSMALL:JNC LCHECK
		 MOV SMALLEST,@BASE
		 SJMP LCHECK
NEWLARGE:JC CONTINUE  
	   	 MOV LARGEST,@BASE
		SJMP CONTINUE
LOOP:SJMP LOOP
END	  																													